POST http://localhost:1337/cctv/cctv-location
Content-Type: application/json

{
   "nama_lokasi": "SP Soekarno Hatta -  Cibaduyut",
   "latitude": "-6.94728",
   "longitude": "107.595227"
}

###
GET http://103.250.10.149:1337/cctv/cctv-location











###
POST http://localhost:1337/cctv/cctv-location/67/list
Content-Type: application/json

{
   "nama_cctv": "TEST",
   "stream": "https://atcs-dishub.bandung.go.id:1990/PajajaranBarat/index.m3u8"
}

###
GET http://localhost:1337/cctv/cctv-location/11/list
Content-Type: application/json

###
GET http://localhost:1337/cctv/cctv-location/67/list/





###





###
GET https://pelindung.bandung.go.id:8443/api/cek


###
GET http://localhost:1337/cctv/cctv-location/seeder

###
GET http://localhost:1337/cctv/cctv-list/seeder

###
GET http://localhost:1337/cctv/cctv-location/11

